name: 'App Pool Status'

description: 'This action will return the status of an IIS app pool hosted by an on-premises server'

inputs:
  server:
    description: 'The name of the target server'
    required: true
  app-pool-name:
    description: 'IIS app pool name'
    required: true
  service-account-id:
    description: 'The service account name'
    required: true
  service-account-password:
    description: 'The service account password'
    required: true
  server-public-key:
    description: 'Path to remote server public ssl key'
    required: true

outputs:
  app-pool-status:
    description: 'The status of the IIS app pool'
    value: ${{steps.action.outputs.app-pool-status}}

runs:
  using: 'composite'
  steps:
    - name: Action
      id: action
      shell: powershell
      run: |
        $secure_password = ConvertTo-SecureString -String ${{ inputs.service-account-password }} -AsPlainText -Force
        ${{ github.action_path }}/iis_action.ps1 `
          -server ${{ inputs.server }} `
          -app_pool_name '${{ inputs.app-pool-name }}' `
          -user_id '${{ inputs.service-account-id }}' `
          -password $secure_password `
          -cert_path '${{ inputs.server-public-key }}'
